src/Table/Table.js, src/Table/table.less
@jesselash thinks the arrow flip doesn't add anything to the experience.
=> remove list sort animation

.travis.yml, src/Modal/__tests__/ModalContents-test.js
=> clean travis-ci setup

src/Modal/modal.less
The modal needs to appear above the side panel.
=> Increase z-index of modal

docs/src/Dropdown/index.js, src/Dropdown/Dropdown.js, src/Dropdown/dropdown.less
Also adds the ability to render the menu up or down, depending on which direction has the most available space.
=> Add maximum height & gemini scrollbar

docs/src/index.less, npm-shrinkwrap.json, package.json
Making sure canvas is up to date
=> Updating canvas

src/Table/Table.js
An example use case for this is if you add class names based on how many columns there are. (Perhaps you wouldn't want to highlight the column if it is the only column)
=> Pass columns into Table column #getClassName

src/Util/Util.js
This follows how `lodash` implements these functions
=> Moving internal funcitons to private scope

.editorconfig, CONTRIBUTING.md, README.md
Updated Contributing guidelines and reame.
=> Add editor config.

src/Table/Table.js
* removes the concept of `visibleItems` in table. we were using it to determine the `scrollDelay` and `itemBuffer`, but those two are now constants.
=> Remove visibleItems code in table

src/Table/Table.js
Also: added `dontCache` functionality to column props
=> Cache row cells instead of rows

src/Table/Table.js
Currently it is a bit of an easter egg (':
=> add dontCache to Table proptypes

docs/src/Form/index.js, docs/src/index.html, docs/src/index.less, src/Form/FieldCheckbox.js, src/Form/FieldInput.js, src/Form/FieldPassword.js, src/Form/Form.js, src/Form/ItemCheckbox.js, src/Form/__tests__/FieldCheckbox-test.js, src/Form/__tests__/FieldInput-test.js, src/Form/form.less, src/Util/Util.js, src/index.less
=> Adding first form example, ref. DCOS-4245

npm-shrinkwrap.json, package.json
Reverts mesosphere/reactjs-components#148
=> Revert "Version 0.0.34"

docs/gulpTasks.js, gulpfile.js, src/Util/Util.js
Reverts mesosphere/reactjs-components#146
=> Revert "Cleaning up build files"

docs/src/Table/index.js, src/VirtualList/VirtualList.js
* put infinite scroll table within a container to not make the docs hard to navigate
* have VirtualList setState in `willMount`
=> Edit docs for Table

npm-shrinkwrap.json, package.json
Included in this patch update: fixes to `Form` and `Table`.
=> bump version to 0.0.35

src/Dropdown/dropdown.less
```
<Dropdown
buttonClassName="button button-inverse dropdown-toggle"
dropdownMenuClassName="dropdown-menu inverse"
dropdownMenuListClassName="dropdown-menu-list"
dropdownMenuListItemClassName="clickable"
wrapperClassName="dropdown" 
... />
```
Previously:
Now:
:+1:
=> Dim inverse Dropdown hover colour

src/Form/form.less
=> Inverse styles for disabled checkboxen

docs/src/Table/index.js
There are no more transitions in Tables
=> Remove transition examples in docs

docs/src/Table/index.js, src/Table/Table.js
```
// Optional selector of the parent element that has a scrollbar in order to
// listen to its scroll event.
containerSelector: PropTypes.string
```
=> clarify table prop doc

docs/src/Tooltip/index.js, docs/src/index.html, docs/src/index.less, docs/styles/example-block.less, main.js, src/Tooltip/Tooltip.js, src/Tooltip/__tests__/Tooltip-test.js, src/Tooltip/tooltip.less, src/Util/DOMUtil.js, src/index.less
The tooltip component has the concept of `position` and `anchor`. `position` refers to the position of the tooltip relative to its trigger (which is its children), and acceptable values are `top`, `right`, `bottom`, and `left`. `anchor` refers to where the tooltip is anchored on the triggered element, and acceptable values are `start`, `center`, and `end`. Think of flexbox alignment when thinking about the `start` and `end` values.
=> DCOS-2044: Add tooltip component

package.json
=> 0.14.0-beta.4

src/Util/DOMUtil.js, src/VirtualList/VirtualList.js
Table would not show up in some cases with the Table component
=> Fixing IE scrollTop bug

src/Form/FieldCheckbox.js, src/Form/__tests__/FieldCheckbox-test.js
Add optional `checked` and `startValue` prop types and fix the startValue all corresponding tests.
/closes #238
=> Add optional checked and startValue prop types

docs/src/Form/index.js, src/Form/FieldTypes.js
=> Add number field

package.json
Reverts mesosphere/reactjs-components#264
=> Revert "Version 0.14.0-beta.19"

docs/src/Form/index.js, docs/src/index.less, src/Form/FieldCheckboxMultiple.js, src/Form/FieldRadioButton.js, src/Form/FieldTypes.js, src/Form/Form.js, src/Form/ItemCheckbox.js, src/Form/__tests__/FieldRadioButton-test.js, src/Form/form.less, src/Form/icons/IconRadioButton.js, src/Util/global.less
=> [1 of 2 Radio Button/Checkbox]  Adding radio button to forms

docs/src/Form/index.js, src/Form/FieldSelect.js, src/Form/FieldTypes.js, src/Form/__tests__/FieldSelect-test.js
This adds a field select component. I am missing tests but it would be great to get already some comments on the component.
=> Add field select component

CHANGELOG.md
=> Add CHANGELOG entry for FieldSelect component

CHANGELOG.md
Change log entry for PR https://github.com/mesosphere/reactjs-components/pull/257
=> Added changelog entry for support for focus on text fields

CHANGELOG.md, src/Form/Form.js, src/Form/__tests__/Form-test.js
This makes it so that only the keys that are different in the definition, are merged into the model
=> Refactor Form model merge into function

src/Form/FieldRadioButton.js
Follow up for this PR: https://github.com/mesosphere/reactjs-components/pull/279
=> Naming error

src/Modal/ModalContents.js
This is needed for dcos/dcos-ui#410
=> Add capability to render nodes in the modal header

CHANGELOG.md, src/Form/FieldSelect.js
Remove the FieldSelect options id to lower case calls.
Closes #289
=> Don`t transform field select ids

src/Form/FieldCheckbox.js, src/Form/FieldInput.js, src/Form/FieldRadioButton.js, src/Form/FieldSelect.js, src/Form/FieldSubmit.js, src/Form/FormControl.js
This improves performance in huge forms by a large degree
=> Form fields only update if props change

src/Modal/ModalContents.js
New props to separately disable the modals transitions:
```
transitionsIn: PropTypes.bool
transitionsOut: PropTypes.bool
```
Also cleaning up unused props!
=> Allow modal to enable and disable transitions

docs/src/index.html, docs/styles/page-header.less
**Option 1**
**Option 2**
**And it moves**
=> Adds octocat image instead of text link

src/Form/FieldSelect.js
This will only make a difference when #316 merges.
=> Pass matchButtonWidth to Dropdown

src/Form/FieldInput.js, src/Form/FieldSelect.js
Make sure to be more liberal in the values accepted by different fields in the form component
=> Fix form prop definitions

docs/src/Dropdown/styles.less, docs/src/Tooltip/styles.less, docs/styles/index.less
This just makes the docs look a little bit nicer :)
=> [CNVS Upgrade] Update docs styles

docs/src/Form/index.js, src/Form/FieldInput.js
This adds the ability to have help blocks in addition to error messages
=> Add help block to input field

package.json
=> Version 0.15.0-beta.0

docs/src/Form/index.js
@mlunoe Noticed the docs didn't store the form's state, so the checkbox and radio fields didn't update on user input.
=> Fix boolean field values

src/Form/styles.less
This PR removes the margin from the last row in a form.
=> [CNVS Upgrade] Fix form's last row's margin

docs/src/Form/index.js
Somehow I missed this guy... 👎
=> [CNVS Upgarde] Fix missing dependency

jest/setupEnv.js
This PR implements an actual polyfill for `requestAnimationFrame` for jsdom.
=> Implement a better requestAnimationFrame polyfill

src/Dropdown/Dropdown.js, src/Dropdown/__tests__/Dropdown-test.js, src/Dropdown/styles.less
This relies on #366 
This PR makes use of the `Portal` element in the `Dropdown` to reliably render outside of the new `Modal`s.
=> [CNVS Upgrade] [Dropdown: 2 of 2] Use Portal in Dropdown

docs/src/Form/index.js
=> Adding change handler to form

.travis.yml, package.json
~~ℹ️  it also contains code from #389 and #388~~ Merged!
I did `npm run livereload` and all widgets seemed to be working
=> Allow react 15.0.0 and 15.4.0

src/Modal/ModalContents.js, src/VirtualList/__tests__/VirtualList-test.js
After some changes to VirtualList and Modal we had some linting errors land on master. This PR fixes that.
=> Fix linting errors on master

.travis.yml, package.json
There were some critical fixes in react lately, let's upgrade 💪
=> chore(react): upgrade react 15.6.1

src/Form/FieldInput.js
Since name is a required attribute it's better to explicitly add it to the field
=> Fix missing name attribute

.travis.yml, CONTRIBUTING.md, install_react.sh, package.json
Adding react 16 support 🎉 
✅  https://github.com/noeldelgado/react-gemini-scrollbar/pull/36
=> Add react 16 support

docs/styles/components/fill/variables.less, docs/styles/layout/navigation.less, docs/styles/layout/page-header.less, docs/styles/layout/sidebar.less, src/Table/styles.less, src/Tooltip/variables.less
It has been replaced with @grey-dark in CNVS
This PR fixes our `npm run dist` and fixes docs build.
=> Fix missing @neutral color variable

docs/styles/components/fill/variables.less, docs/styles/layout/navigation.less, docs/styles/layout/page-header.less, docs/styles/layout/sidebar.less, package.json, src/Table/styles.less, src/Tooltip/variables.less
To keep the master compatible with DCSO-UI we have to revert @neutral fix and lock CNVS version 1.1.9
=> Revert @neutral fix and lock CNVS version 1.1.9

src/Dropdown/Dropdown.js
Remove DropdownTrigger import to fix lint issues
=> fix(Dropdown): remove unused variable

main.js
We've forgotten to export the abstract class 😅
=> Export DropdownTrigger from the package

src/Select/Select.js, src/Select/SelectOption.js, src/Select/__tests__/Select-test.js
=> fix(Select): use es6 exports as used in main.js

docs/styles/components/fill/variables.less, docs/styles/layout/navigation.less, docs/styles/layout/page-header.less, docs/styles/layout/sidebar.less, package.json, src/Table/styles.less, src/Tooltip/variables.less
Bump CNVS to latest version. Resolve variable inconsistencies.
JIRA: https://jira.mesosphere.com/browse/DCOS_OSS-1774
=> [DCOS_OSS-1774] CNVS bump

.travis.yml, install_react.sh
=> Test react 16.1 and 16.2

src/Confirm/Confirm.js
The goal of this PR is to align all modal designs with our UI Kit. In particular, the size of modals, the layout, the heading alignment and the alignment of buttons.
In order to make this sweeping change, there are updates required in this repo, the enterprise repo and the reactjs components repo.
See https://github.com/dcos/dcos-ui/pull/2485 for detailed info.
=> DCOS_OSS 1783 Update modals to match UI Kit

src/Select/Select.js, src/Select/SelectOption.js, src/Select/__tests__/Select-test.js
This PR fixes the issue, that the select wasnt rerender itself when props changed.
=> DCOS-19864: Fix select

src/Dropdown/DropdownListTrigger.js
=> fix(dropdown): changes proptype 'function' to 'func'

docs/src/index.js
=> fix(docs): update link to cnvs

src/Dropdown/Dropdown.js
Enforce dropdow to close on window resize
Closes DCOS-39951
=> feat(Dropdown): close on window resize

jest/config.json, package-lock.json, package.json
=> chore: update babel and jest

src/Dropdown/Dropdown.js, src/Form/FieldCheckbox.js, src/Form/FieldInput.js, src/Form/FieldTextarea.js, src/Modal/ModalContents.js, src/Table/Table.js, src/Tooltip/Tooltip.js, src/Tooltip/__tests__/Tooltip-test.js, src/Util/DOMUtil.js, src/VirtualList/VirtualList.js
Turned out we don't check refs before using them. That PR fixes that.
This one also resolves react16 refs :)
=> fix: check all refs before use

src/Select/Select.js
See https://stackoverflow.com/a/46012210/1559386 for reference
=> fix(react): react 16 breaks overwrites the set attribute on inputs

.travis.yml, docs/src/index.js, install_react.sh, package-lock.json, package.json, src/Dropdown/Dropdown.js, src/Form/FieldInput.js, src/Form/FieldTextarea.js, src/Modal/ModalContents.js, src/Select/Select.js, src/Table/Table.js, src/Tooltip/Tooltip.js, src/Tooltip/__tests__/Tooltip-test.js, src/VirtualList/VirtualList.js
Additionally this adds some safe guards, so we don't fail with missing
properties
=> fix(Dropdown): ref was called without current

.travis.yml
test matrix takes care of `npm test`
=> ci: remove extra stage

src/Dropdown/Dropdown.js, src/Form/Form.js, src/Form/__tests__/Form-test.js, src/Mixin/BindMixin.js, src/Modal/ModalContents.js, src/Portal/Portal.js, src/Table/Table.js, src/Util/Util.js, src/VirtualList/VirtualList.js
Everything should still work the same as before.
=> Rename React methods
