mesosphere/reactjs-components

- src/Table/Table.js
This fixes a bug revealed in the groups table in DCOS UI.
> Prevent rendering a non-scrollable table when dataset length is 0

- src/Table/Table.js
- src/VirtualList/__tests__/VirtualList-test.js
So our previous solution forces the scrollTable to render under certain conditions, but didn't account for an empty dataset. This fixes that.
> Fix error when rendering empty dataset

- src/Dropdown/Dropdown.js
- src/Dropdown/__tests__/Dropdown-test.js
- src/Dropdown/dropdown.less
- src/VirtualList/__tests__/VirtualList-test.js
Reading the component's code might be a little confusing, so here's an overview of what happens:
1. The first time the dropdown opens, it renders inside a hidden element with class `dropdown-menu-concealer`
2. Immediately afterwards, `componentDidUpdate` measures the concealed menu, as well as the dropdown button's position in the viewport, and the viewport height, and updates the state with the correct position for the menu (`up` or `down`)
3. The component renders again with the correct `up` or `down` classes & animations, and without the concealer
4. Every subsequent time the dropdown opens, it calculates the direction at the same time it toggles its `open` state.
> Allow dropdown to appear above dropdown button if viewport is too small

- src/Table/Table.js
- src/Table/__tests__/Table-test.js
- src/VirtualList/VirtualList.js
* removes GeminiScrollbar from Table
* does not cap height of Table
* adds containerSelector functionality (ex. pass in `.container` and it will find the closest ancestor and use that as the container)
* only use a single table, instead of having two tables (for scrollbar)
> Do not cap height of Table

- src/Util/Util.js
- src/Util/__tests__/Util-test.js
- src/VirtualList/VirtualList.js
- src/VirtualList/__tests__/VirtualList-test.js
* remove the concept of `itemsInView` and use strictly `firstItemIndex` / `lastItemIndex`
* if container changes, reset scroll listeners
* throttle instead of debounce scroll event
> Remove unnecessary code in VirtualList

- main.js
- src/Form/Form.js
Using `module.exports = {Component}` in compliance with Babel 6
> fix Form module export

- src/Modal/ModalContents.js
- src/Modal/__tests__/ModalContents-test.js
Currently, if the modals are capped out at the `maxHeight` and the maxHeight gets bigger, the modal doesn't also get bigger. This fixes that.
> Allow modals to get bigger as the viewport gets bigger

- docs/src/Form/index.js
- src/Form/FieldCheckbox.js
- src/Form/FieldInput.js
- src/Form/__tests__/FieldCheckbox-test.js
- src/Form/__tests__/FieldInput-test.js
the `showLabel` prop inside of definition can now have three possible value types:
* **boolean**: if true, will show the field name as a label. if false, will show nothing.
* **string**: will use string as label.
* **function**: will invoke and return the result of the function
> Allow a custom function to be passed into showLabel

- docs/src/Table/index.js
- src/VirtualList/VirtualList.js
Was trying to be clever before and only show 1 item when table was no on screen. This caused problems because if the container wasn't the window, it wouldn't refresh and show the full items when it was on the screen.
This fix will now show the necessary items whether the table is on the screen or not
> Don’t show a single item when table not on screen

- src/Form/FieldInput.js
- src/Form/FieldPassword.js
- src/Form/Form.js
- src/Form/__tests__/FieldInput-test.js
- src/Form/__tests__/Form-test.js
This introduces two features:
* Allows users to pass a custom `render` function for each form element. The custom `render` function receives the input element and is expected to return a transformed element, or the same element, in its place.
* Allows users the ability to pass components as items in the `definition` array, which will not be modified in any way by the component.
> Allow react elements in definition, allow custom render functions

- src/Form/FieldPassword.js
This removes the default password string, which displayed the same string for password fields whenever they were not in focus.
By default it will behave as a regular password input field, where it's empty to start and then displays the obfuscated password as the user enters it. On blur, the obfuscated password remains.
Users can specify a `defaultPasswordValue` which will be displayed when a password field does not have focus, in order to hide the length of the actual password in the input field.
In this example, the `defaultPasswordValue` is set to a two-character string:
> Remove default password

- docs/src/Table/index.js
- src/Table/Table.js
Turning caching on by default makes the table harder to use up front + caching is only for niche cases.
> Turn table cell caching off by default

- src/Form/FieldPassword.js
- src/Form/Form.js
For each event, `handleEvent` will pass the `fieldName` and `fieldValue` of the element that triggered the event, as well as the event object itself.
> Extend handleEvent to pass more event information

- src/Form/Form.js
The `eventType` (blur, focus, change) needs to be passed back to the `onChange` handler.
> Add eventType to eventObject that gets passed to onChange handler

- docs/src/Modal/index.js
- src/Modal/ModalContents.js
- src/Modal/__tests__/ModalContents-test.js
Changes to Modal: allow disabling of gemini scrollbar and allow disabling of dynamic height adjustment. Disabling scrollbar allows for components to overflow the modal (such as dropdown).
```
<Modal
dynamicHeight={false}
useGemini={false}
... >
```
> Expose scrollbar and height adjustment in Modal

- docs/src/Table/index.js
- src/SidePanel/SidePanelContents.js
- src/overrides/gemini-scrollbar.less
This fixes a problem with the side panel, where the contents wouldn't scroll when Mac OSX scrollbar setting was set to: "Automatically based on mouse or trackpad" and a mouse or external trackpad is used.
> Fix side panel scroll

- src/Modal/modal.less
This was causing the `Confirm` modal (which doesn't have `.modal-large` to have weird widths at small screen sizes
> At super small widths, have the width property apply to all modals

- src/Table/table.less
Removing cursor type style to allow elements within table to set their own cursor types.
> Remove cursor type override

- docs/src/Tooltip/index.js
- src/Tooltip/Tooltip.js
- src/Tooltip/tooltip.less
* Use of the `anchor` prop will now align the tooltip's arrow
at 50% of the width or height (depending on the `position`
prop), and the Tooltip's content will then be anchored
according to the prop definition.
* Allows custom DOM node to be used
* Pass all props that aren't specific to Tooltip to the node
* Remove specific margin styling
> Improve tooltip.

- src/Form/FieldCheckbox.js
- src/Form/FieldCheckboxMultiple.js
- src/Form/FieldInput.js
- src/Form/ItemCheckbox.js
All the classes are the same. There is just the ability to override classes you don't want now.
> Allow form-row-element to be overridden

- src/Table/Table.js
This is useful because if the data doesn't have the prop at the top level, using `row[prop]` won't work (for example, you'd have to go inside a `resources` object to retrieve the value like so: `row.resources[prop]`.
> Allow columns to have custom value getters

- src/Util/Util.js
- src/Util/__tests__/Util-test.js
Create copy of collection before sorting it to not mutate the original collection. Added test to verify correct behaviour.
/closes #239
> Fix Util.sortBy to not mutate collection

- docs/src/Tooltip/index.js
- src/Tooltip/Tooltip.js
- src/Tooltip/__tests__/Tooltip-test.js
- src/Tooltip/tooltip.less
- src/Util/DOMUtil.js
This uses the portal and will work everywhere (even inside a container with `overflow: scroll`). That introduced a fair amount of additional logic to determine the position of the tooltip trigger and the ideal location for the tooltip content.
> Use Portal for Tooltip

- docs/src/Tooltip/index.js
- src/Tooltip/Tooltip.js
* `suppress` to prevent the Tooltip from displaying
* `stayOpen` to keep the tooltip open after it's triggered
* `triggerTooltip` to manually trigger it from outside the component
> Add several options to the Tooltip component.

- src/Modal/ModalContents.js
This fixes an height update problem with modal. It would not update the height unless you explicitly updated the the container of the component twice.
Before:
After:
> Fix update height issue in modal

- src/Form/FieldTextarea.js
Textareas are multiline input fields which should not be blured
if the `Enter` key is pressed.
As an example of the problem please take a look at the message text area at http://mesosphere.github.io/reactjs-components/#form
> Remove onKeyDownHandler on Textareas

- docs/src/index.less
- package.json
- src/index.less
it seems like we depended on `react-gemini-scrollbar` to ship with its own `node_modules` which isn't the case anymore. I did a fresh `npm install` and I get the following:
```
✘  ~/Development/reactjs-components   master ●  npm run livereload
> reactjs-components@0.14.0-beta.18 livereload /Users/pierlo/Development/reactjs-components
> NODE_ENV='development' ./node_modules/.bin/gulp docs:livereload
[13:56:35] Using gulpfile ~/Development/reactjs-components/gulpfile.js
[13:56:35] Starting 'docs:webpack'...
[13:56:35] Starting 'docs:eslint'...
[13:56:35] Starting 'docs:less'...
[13:56:35] Starting 'docs:html'...
[13:56:35] Starting 'docs:browsersync'...
[13:56:35] Finished 'docs:browsersync' after 20 ms
[13:56:35] Starting 'docs:watch'...
[13:56:35] Finished 'docs:watch' after 21 ms …
```
> Fix missing gemini scrollbar import

- docs/src/Form/index.js
- src/Form/FieldInput.js
- src/Form/__tests__/FieldInput-test.js
This PR enables to specify an input field (of type text) to be focused and with the cursor set at the end of the input whenever a default value is specified.
Example usage
> Add support for focused option for input fields

- src/Form/FieldCheckbox.js
- src/Form/FieldRadioButton.js
- src/Form/Form.js
- src/Form/__tests__/FieldCheckbox-test.js
Aligning checkbox, with how it used to work before.
To adhere to the radio buttons requirements of having multiple fields change at the same time, arrays were passed to the `onChange` handler, and for checkboxes that meant that arrays of singe items was being passed. This, however, doesn't make too much sense for the users perspective, so I changed the handler to handle both cases, i.e. _arrays_ (for radio buttons) and _single items_ (for checkboxes).
> Checkbox radio button follow up

- CHANGELOG.md
- src/Form/Form.js
In certain scenarios, an outdated model would be returned to the `onChange` handler, since `setState` is asynchronous.
This PR fixes that problem and makes sure to always return the most up-to-date model on change
> Form return updated model on change

- src/Form/Form.js
that happens if we make it a variable. it needs to be `this.props.formTag`
> Don't make formTag a variable

- src/Form/FieldSelect.js
If we provide a string as `startValue` then we want it to match an existing option first (if one is available).
> Find existing ID in dropdown options

- src/Table/Table.js
- src/Table/__tests__/Table-test.js
Fixes bug where the `Table` would not obey its initial sort order.
> Properly obey initial sort order

- CHANGELOG.md
- src/Modal/ModalContents.js
This PR moves the padding for the modal's content to inside the scroll container.
Here it is in action:
> Move padding to inside of scroll container

- src/Form/Form.js
Before, the form would get errors from definition + it'll keep it's own state from user interaction for errors. This props make it so that errors are completely driven from the form definition.
> Add useExternalErrors prop to Form

- src/Dropdown/Dropdown.js
- src/Dropdown/dropdown.less
This PR changes the dropdown to use fixed positioning, which allows it to render outside of elements whose overflowing content is clipped.
See it in action:
It will close automatically when its parent container scrolls.
One breaking change was introduced with this refactor. To anchor dropdowns to the right of the dropdown button, we must now do it via a boolean passed to the `Dropdown` called `anchorRight`. This is due to the fixed positioning.
> Use fixed positioning for Dropdown

- src/Dropdown/Dropdown.js
- src/Util/DOMUtil.js
This PR introduces the ability to provide a selector via the prop `scrollContainerParentSelector`. If it matches the parent of the `scrollContainer` element, the scroll event handler will be attached to the parent element rather than `scrollContainer`.
This is necessary due to Gemini changing which element handles overflowing content dependent upon OS-specific settings. If the OS does not render overlay scrollbars, Gemini handles scrolling in a div with class `gm-scroll-view`. If the OS does render native overlay scrollbars, Gemini does nothing except add DOM nodes, so the direct parent of the Gemini component is left responsible for the scroll behavior.
This PR also exposes the `matchesFn` in `DOMUtil` which is now consumed by the `Dropdown`.
> Find native scroll container if Gemini isn't needed

- package.json
Currently, I have the `npm publish` in the `postversion` script. the `postversion` automatically tags the publish with the version, which means it won't be on `latest`. the functionality will have to change if we ever want to create a `release-patch` script
> Add release-beta script

- CONTRIBUTING.md
- package.json
This PR prepends the text `version-` to the version tag, because NPM rejects any tag that begins with `v` or a number. It also fixes the `CONTRIBUTING.md` document to include the usage of the script.
> Fix beta release script

- src/Dropdown/Dropdown.js
This PR sets the `left` and `right` properties of the dropdown menu to match the `left` and `right` position of the dropdown button.
> Add support for dropdown menu matching button width

- src/Form/Form.js
This will make sure to return updated model on triggerSubmit in onChange callback
Related change: https://github.com/mesosphere/reactjs-components/pull/280/files#diff-035be6cdc63453ed42b5cf6b6fcf34b8R123
> Make sure to call form on change after state has been set

- src/Form/FieldInput.js
- src/Form/FieldTextarea.js
- src/Form/form.less
This PR replaces all `textarea` elements with `div` elements with `contenteditable="true"`.
It seems to work inside DCOS UI, but please test this heavily.
> Implement auto-expanding "TextArea"

- docs/src/components/CodeBlock.js
- docs/src/components/CodeBlockWrapper.js
- docs/src/components/ComponentExample.js
- docs/src/components/ComponentExampleWrapper.js
- docs/src/components/ComponentWrapper.js
- docs/src/components/PropertiesAPIBlock.js
This PR introduces reusable components to be used in our docs. This removes a lot of the repetition in assigning classes and structuring DOM elements.
> [CNVS Upgrade: Docs] Add reusable components for creating our docs

- src/Modal/ModalContents.js
- src/Modal/styles.less
- src/Modal/variables.less
- src/index.less
This PR...
* Updates the modal header to use `h2`
* Moves the `CSSTransitionGroup` to the entire component, rather than using two
* Previously we used two: one for the backdrop and one for the modal, resulting in extra DOM operations. Now, we still animate both independently, but we use a single parent's classname to trigger the animations.
* Adjusts the entrance and exit animations...
* We animated the modal's position by a percentage of its height, so each modal's position was animated differently. Now it's a fixed 50px always.
* The animation length was 0.5s, which felt long. Now it's 0.3s
* Uses the `ease` timing function which feels less like the modal is crashing into place
* Removes a seemingly unnecessary DOM node which wasn't being used in DC/OS UI (was given classes in prop …
> [CNVS Upgrade] Update Modal to use new CNVS markup and improve its animations

- src/Dropdown/Dropdown.js
This fixes a bug where the height of the dropdown wasn't calculated properly when Gemini scrollbar was being used in conjunction very long menu.
When a very long dropdown menu rendered for the first time (so it hasn't yet calculated how tall the dropdown menu is), it would render with Gemini (if the props allowed it). This poses a problem because Gemini implements logic to measure its parent's height and then caps the content at this specific height. In the case of the `position: fixed` dropdown, Gemini cannot calculate the parent's height accurately.
Now, when a very large dropdown is rendered and the maximum height of the dropdown has not already been measured, it renders without Gemini, so all subsequent calculations of height are based on the "natural" height of the menu. After the …
> Fix dropdown height calculation

- src/Form/FormControl.js
This PR adds an option to provide a key in the field definition, instead of using the name
> Add option to provide key in definition

- src/Form/form.less
This PR removes additional styling from children of `.content-editable` to prevent things like the following:
> Remove more styling from content-editable children

- src/Modal/ModalContents.js
- src/Modal/__tests__/ModalContents-test.js
This PR allows users of the `Modal` to pass an element to use for a close button.
Previously there was a boolean property, `showCloseButton`, which rendered a specific set of nodes. Now, there is a `closeButton` prop which will cause a render of a `button` element with the provided node as its child.
> [CNVS Upgrade] Allow custom close button

- src/Confirm/Confirm.js
This PR just removes the `scrollContainerClass` prop because it is not necessary.
> [CNVS Upgrade] Remove Confirm modal's scrollContainerClass prop assignment

- src/Modal/ModalContents.js
- src/Modal/styles.less
This PR removes all the custom padding from `reactjs-components` and relies on CNVS to set the padding.
> [CNVS Upgrade] Fix modal body classes to match new CNVS styles

- src/Form/styles.less
This prevents the following from happening:
> [CNVS Upgrade] Fix content-editable div styling

- src/Modal/styles.less
This was mistakenly removed in a rebase, so I'm just adding it back to fix the modal's exit animation.
> [CNVS Upgrade] Add missing transition property

- docs/src/Modal/index.js
- jest/setupEnv.js
- src/Confirm/Confirm.js
- src/Modal/ModalContents.js
- src/Modal/__tests__/ModalContents-test.js
- src/Modal/styles.less
This PR aims to simplify the height calculation logic of the `ModalContents` component.
Highlights:
* We use `setState` instead of `forceUpdate` to re-render the modal.
* We calculate the height of the content only when absolutely necessary.
* We make use of `requestAnimationFrame` to help reduce jank.
* The maximum height of the modal is determined by CSS rather than with the `maxHeightPercentage` prop.
* The props API of this component was reduced significantly.
* When `useGemini` is set to `false` (which is now _default_), there is no height calculation done at all.
> [CNVS Upgrade] Refactor modal height logic

- src/Form/styles.less
This gives proper padding to the `.content-editable` class. It doesn't come with `.form-control` out of the box because the `.form-control` elements have a fixed height. Thanks @Poltergeist for noticing!
> Give "textarea" padding on top and bottom

- src/Form/icons/IconCheckbox.js
- src/Form/icons/IconRadioButton.js
The `hidden-up` class no longer exists; it's now just `hidden`.
> [CNVS Upgrade] Fix hidden-up class

- src/Modal/ModalContents.js
- src/Modal/styles.less
This PR corrects a bug, where modals would not stack correctly.
Before: | After:
------------ | -------------
> Making modals stack on top of each other when multiple are open

- src/Table/styles.less
This PR toggles the `display` property rather than `opacity` and `visibility`. This will prevent the caret from affecting layout when it's invisible.
It does mean that center-aligned table headings will jump around when their sorting is toggled. I discussed this solution with @ashenden and he's on board.
> Toggle display property for caret

- src/Tooltip/styles.less
This gif shows the issue where we need the tooltip to be display `block`, where it is `inline-block`:
> Add block class for tooltip

- src/Modal/ModalContents.js
This PR allows passing a `modalHeight` prop. When defined, this prop will be assigned to the height of the Gemini wrapper rather than be calculated automatically.
This fixes a bug discovered where the child components would lose their state. Before this PR, the component renders initially without Gemini, then calculates the height of its content. If the height of the content exceeds the container, then it re-renders the content wrapped in Gemini. With this property, we can avoid conditionally rendering the Gemini wrapper.
> DCOS-11732: Allow passing modal height to ModalContents

- src/VirtualList/VirtualList.js
---
Same fix as here: https://github.com/mesosphere/reactjs-components/pull/384
---
This PR fixes a bug where the scroll listeners would not bubble to parent elements and would therefore not be able to listen to events higher in the bubble chain.
> Scroll event not being bubbled in virtual list, ref. DCOS-11781

- package.json
- src/Form/Form.js
Notable updates:
* Updated .button-flush with directional modifiers
* Fixed disabled buttons of type *-link
* Adjusted background of .form-control and .form-control-toggle
* Updated background style of .form-control style variants
* URI encode inline SVG strings
* Updated styling of `disabled` state for `form-control` component
Full diff here for reviewers: https://github.com/mesosphere/cnvs/compare/4e301e8951b74b7c4d6f959ef255651f7da6a11d...d2eb4d1477a0aab827071db210a7c638f9b3cc45
> Updated CNVS from 1.1.3 to 1.1.6

- package.json
Apparently someone had already released beta versions 7 and 8, so I had to jump to 9.
> 0.16.0-beta.9

- .travis.yml
Build is failing because of C++11 issues, this is what I've found https://github.com/travis-ci/travis-ci/issues/4771
Adding these lines seems to fix the build
```yaml
env:
- CXX=g++-4.8
addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:
- g++-4.8
```
> Specify c++ version for Travis build

- .travis.yml
- package.json
This PR updates two dependencies. They were causing the build to fail due to recent internal changes in `stylelint`. 
Related:
https://github.com/olegskl/gulp-stylelint/issues/57
> Update stylelint deps

- src/VirtualList/VirtualList.js
Closes DCOS-12966
This PR binds the onScroll function to the right context, so we don't hit this error again:
> DCOS-12966: Make virtual list bind its onScroll function correctly

- src/Dropdown/Dropdown.js
This PR explicitly sets positioning values to `auto` rather than relying on their default properties. This fixes a bug in IE11 where the dropdown would be rendered flush with the left edge of the viewport.
Before:
After:
> DCOS-14092: Explicitly set dropdown positioning properties to auto

- CONTRIBUTING.md
- package.json
This PR makes it easier for us to create releases and automates the process of committing and pushing tags in addition to previous release steps.
See guide to use here: https://github.com/mesosphere/reactjs-components/blob/623b58b6cdacb5c0344ed8a669506d8f026518f8/CONTRIBUTING.md#publishing-a-new-release
> DCOS-12721: Push commit and tags in release script

- src/VirtualList/VirtualList.js
This PR ensures we are removing the scroll event listener properly. Previously we attached the listener with event capturing, but removed it without capturing. This PR removes the capturing boolean because we don't need it.
> DCOS-12966: Properly remove event listener

- src/Modal/ModalContents.js
- src/Modal/__tests__/ModalContents-test.js
This PR fixes the modal height calculations for IE11. Here's a gif!
Before:
After:
> DCOS-14141: Fix modal height calculations in IE11

- src/Tooltip/Tooltip.js
This PR reduces the scroll event listener logic for the `Tooltip` component. It will now attach its scroll event listeners to the `window` object in the capture phase so that it's the first listener called when a scroll event happens anywhere in the UI.
This means that the consumers of the `Tooltip` doesn't need to worry about which element to attach the event listener.
> DCOS-14370: Reduce scroll event listener logic in Tooltip

- src/Form/FieldCheckbox.js
- src/Form/FieldInput.js
- src/Form/FieldRadioButton.js
- src/List/List.js
- src/List/ListItem.js
- src/Tooltip/Tooltip.js
- src/VirtualList/VirtualList.js
This PR addresses all the react 15.4.x warnings by filtering the attributes we provide to tags.
> fix(react-15): exclude prop types from html attributes

- docs/src/Tooltip/index.js
`scrollContainer` prop has been long gone from `Tooltip` though it is still in the docs. This PR fixes it.
> docs(Toolbar): remove deprecated scrollContainer

- docs/src/Dropdown/index.js
- src/Dropdown/Dropdown.js
- src/Dropdown/__tests__/Dropdown-test.js
This adds a disabled state in the dropdown. It is like the "select" element where you can just add a disabled attribute and it disables the dropdown.
Add disabled state in Dropdown.
Include doc page for disabled instance.
Include test for disabled Dropdown instance.
> Dropdown: Add disabled state in dropdown

- docs/src/Select/index.js
- docs/src/index.js
- main.js
- package.json
- src/Select/Select.js
- src/Select/SelectOption.js
- src/Select/__tests__/Select-test.js
**⚠️  ~~depends on #418~~** 
This component wraps the existing Dropdown, but also adds an input field which
enables us to emit proper onChange events.
Example Usage (can be used for testing):
```
outdated, see comment below
```
This exact example is from the `Create Service > Volumes > Local Volumes` Select, you can replace the existing one after linking the branch from `reactjs-components` and importing it.
Closes DCOS-19313
> feat(select): create a new select component wrapping the existing dropdown

- package.json
`react-gemini-scrollbar` 2.2.0 bumped `gemini-scrollbar` that introduced an `<object>` element to tract element resize events. 
This change confuses `cypress` and breaks our tests. 
Since we're not using `react@16` right now anyway, it's ok to allow using `react-gemini-scrollbar@2.1.5` until we fix everything and switch to `react@16`
> chore(react-gemini-scrollbar): re-add 2.1.5

- src/Confirm/Confirm.js
Fixes an issue where on smaller screens the primary buttons were not aligned as intended.
Before
After
> refactor(confirmations): Fix alignment for small screens

- src/Dropdown/DropdownListTrigger.js
- src/Dropdown/DropdownTrigger.js
The proptypes package exports `.func` instead of `.function` to test if a prop is a function.
> DropdownTrigger: fix proptype type of function

- src/VirtualList/VirtualList.js
- src/VirtualList/__tests__/VirtualList-test.js
VirtuaList receives as props functions to render its
items when those functions throw, we send react into
havoc and it starts rendering infinite lists. This
fixes this problem by wrapping the functions on try/catch
CLOSES DCOS-21362
Also, trick to test, but you can:
- On your DC/OS UI repo, checkout branch `bug-reproduce-dcos-20507`, commit `b65b398a59c9ac4f784982e77deaddef0345aa50` go to the nodes page and try to filter for Unhealthy, and back. This will set your list into *infinite craziness ™* (from this reproduction PR https://github.com/dcos/dcos-ui/pull/2760)
- link reactjs-components, check out on this branch, and see that the craziness is gone
> fix(VirtualList): prevents render failing on exception

- src/Portal/Portal.js
When calling `ReactDOM.render`, the parent React context is unexpectedly lost, which disconnects portal content with certain integrations that depend on it.
Closes DCOS-43041
In React 16, the React.createPortal API is preferred, but the portal component will need to be restructured because this structure depends on a render callback. The unstable_renderSubtreeIntoContainer API exists in React 16, so this isn't an immediate upgrade concern.
The "unstable" part of the method name reflects the stability of the API, not the behavior ;)
1. Clone the repo, check out the branch
2. run `npm install`, `npm dist-src`, `npm link`
3. change to dcos-ui directory
4. run `npm link reactjs-components` and restart the server, but don't run `npm install`
5. interact with any modal, tooltip, or confirm
> DCOS-43041: Preserve React context when rendering Portals

- .travis.yml
- package-lock.json
- package.json
since dcos-ui embraced node@8 and old npm doesn't support 2FA it would be wise to update the repo even though we aren't actively maintaining it.
> Upgrade node/npm/babel

- package-lock.json
- src/Form/FieldInput.js
- src/Form/Form.js
In order to backport [DCOS_OSS-2065](https://jira.mesosphere.com/browse/DCOS_OSS-2065) to 1.10, we need the Form component to be able to render an HTML form with the `novalidate` attribute, and for number inputs to set a `lang` attribute
> DCOS_OSS-4580: i18n-friendly number input

- src/Table/Table.js
- src/Table/__tests__/Table-test.js
Only use VirtualList for tables with large data sets.
To test in dcos-ui:
- Check out this branch and run `npm run preversion`
- Go to dcos-ui and replace `reactjs-components` version number in package.json with `"file:../path/to/reactjscomponents/repo"`
- Run on soak and look at components that use reactjs-components table (ie Jobs > Detail)
Jobs run history table comparison:
- Before: https://cl.ly/fc46a4c05463
- After: https://cl.ly/34a03ec1ff43
1000 was chosen as a semi arbitrary cutoff for using VirtualList
> fix(Table): don't use virtual list for small tables

- src/Util/Util.js
Prevent the find function from returning undefined in order to fix a dcos-ui bug.
Closes https://jira.mesosphere.com/browse/DCOS-48704
1. In dcos-ui in `dcos-ui/node_modules/reactjs-components/lib/Util/Util.js` in the find function change `return result;` to `return result || {};` on line 472.
2. Run `npm start` and open the localhost.
3. Open Organization > Users.
4. Create a new user and open it.
5. Open the permissions builder modal.
6. Click around and verify that the modal doesn't crash.
Here are some cases that broke it before:
- From `Services -> Marathon -> Operator > Leadership` to `Services -> Marathon -> Operator > Events`.
- From `Admin Router > Services > Metronome (Jobs)` to `Secrets Store`.
- From `Mesos > Master > Framework > Role` to `Mesos > Master > Framework > Service …
> DCOS-48704: Permissions builder exception
